### PR TITLE
Runtime 45

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by bbhtt** [comment]
Crashes immediately while trying to load a tiff file https://file-examples.com/wp-content/storage/2017/10/file_example_TIFF_1MB.tiff

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ShapeError/IncompatibleShape: incompatible shapes', src/lib/tiff.rs:55:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by anieuwland** [comment]
That TIFF is very likely not of the specific format expected by this app and it's therefore okay (although inelegant) that the app crashes. At the very least, it is not a regression :) 

Blackbody serves to view thermograms, e.g. heat imagery, specifically those produced by FLIR cameras. Sometimes people have exported TIFFs as float32, single-banded TIFFs so they can open the files in other software such as Qgis, Python or w/e. Indeed, Blackbody supports exporting an opened FLIR jpeg to such TIFFs and can open those TIFFs again as well.

The linked TIFF has 3 channels (RGB) instead of 1 which is what causes the crash. I suspect the channels are also integers, of a different size than the float32s it expects, which also prevents successfully loading it.

**Comment by anieuwland** [comment]
@bbhtt If you are interested in trying it with a relevant file, try for example flir_e6_3.jpg from [here](https://bitbucket.org/nimmerwoner/blackbody/downloads/).

**Comment by bbhtt** [comment]
Yea seems to work fine :) I'm not a user, just cleaning up apps on old runtimes and testing them.

**Comment by anieuwland** [comment]
I figured, thanks a lot for doing so!

**Pull request merged**
